# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FilterLayersAtOnce
                                 A QGIS plugin
 Filters multiple visible layers at once with attributes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-15
        copyright            : (C) 2020 by Murat Kendir
        email                : muratkendir@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FilterLayersAtOnce class from file FilterLayersAtOnce.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .filter_multiple_layers_at_once import FilterLayersAtOnce
    return FilterLayersAtOnce(iface)
